version = 1

SPDX-PackageName = "maps-sdk-examples-for-android"
SPDX-PackageSupplier = "magiclane-developer@users.noreply.github.com"
SPDX-PackageDownloadLocation = "https://github.com/magiclane/magiclane-maps-sdk-examples-for-android"
SPDX-PackageComment = "Real-world use cases for the Magic Lane Maps SDK on Android to support faster app development and feature exploration."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Magic Lane International B.V. <info@magiclane.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "**/gradle/**",
    "**/gradlew",
    "**/gradlew.bat",
    "**/gradle.properties"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/thirdParty/MPChartLib/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Philipp Jahoda"
SPDX-License-Identifier = "Apache-2.0"
